### ISSUE TITLE
I'm new to neovim, how do I install this plugin?

### ISSUE THREAD

**Issue by afgallo** [tree-sitter/tree-sitter-embedded-template#24]
Sorry can't figure this out, how do I install, use and make sure it's always loaded? BTW I use Astronvim and followed the installation instructions here: https://astronvim.com/. The default plugin manager is lazy.nvim.

Thanks!

**Comment by tymoyato** [comment]
Hi @afgallo I don't know if you managed to install the plugin since 2 weeks,
but I will answer you.

You need to install in treesitter  **embedded_template** and ensure its installed.
You also need to be sure **tree-sitter-embedded-template** plugin is loaded  because it can be lazy loaded (if you use Nvchad for example) I don't know about **astonvim** sorry.
`TSInstall embedded_template `

`ensure_installed = {
   "vim",
   "lua",
   "html",
   "css",
   "javascript",
  "typescript",   
  "tsx",
  "c",
  "markdown",
  "markdown_inline",
  "ruby",
  "embedded_template",
   },    
  embedded_template = {
   enable = true,
  },`

**Comment by afgallo** [comment]
Thanks @tymoyato. Do you happen to know how I do that in the lua configuration file below? You can see that I already had embedded_template in there but it still doesn't work.

```
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    -- add more things to the ensure_installed table protecting against community packs modifying it
    opts.ensure_installed = require("astronvim.utils").list_insert_unique(opts.ensure_installed, {
      "lua",
      "bash",
      "c_sharp",
      "css",
      "dockerfile",
      "html",
      "javascript",
      "json",
      "python",
      "ruby",
      "sql",
      "terraform",
      "typescript",
      "yaml",
      "embedded_template",
    })
  end,
}

```

**Comment by tymoyato** [comment]
@afgallo The configuration file looks good,
did you install the package via Tree-sitter ?

make sure you run 

`:TSInstall embedded_template `

https://astronvim.com/ they explain how to install package for tree sitter

when you have it installed open an **erb** file

run
`:Lazy`

and check if **tree-sitter-embedded-template** is part of plugins that are loaded.

if not check https://astronvim.com/recipes/custom_plugins
about lazy loading

the custom config of your **tree-sitter-embedded-template** 

you must precise the ft (filetype) :
`{ "tree-sitter/tree-sitter-embedded-template", ft = "embedded_template" }`

force loading(not recommended because it will be always loaded even for others files) 
{ "tree-sitter/tree-sitter-embedded-template", lazy = false }

of course you need to save all configurations in case you forget.
maybe reload nvim.

**Comment by Congee** [comment]
Thanks! I have to do `au BufRead *.ejs se ft=embedded_template`. Not sure if that's relevant to AstroNvim
